### ISSUE TITLE
No file/directory

### ISSUE THREAD

**Issue by RetryingOOS** [JustinELRoberts/CookGroupBots#1]
I set up everything correctly but it raises the error. 

`discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Honor\\Downloads\\Cook\\cogs\\../groups/Test Notify/shop/shop.json'`

Can you provide a solution for this? Thanks!!

**Comment by JustinELRoberts** [comment]
Looks like I might have missed some stuff when refactoring awhile back. It should be an easy fix; I'll do it tomorrow or the next day when I get a free hour or two :)

**Comment by RetryingOOS** [comment]
And another question how much members do you think a json file can handle. When might it cause race conditions and be corrupt? Thanks again!

**Comment by JustinELRoberts** [comment]
I'm not quite sure; it would really depend on how active members are. If you are having issues, let me know; I can always just add a SQL database or something

**Comment by RetryingOOS** [comment]
I think that a SQL database would be great. Thanks for your help! Really appreciate it!

**Comment by JustinELRoberts** [comment]
Yeah either would work. I just have to find the time to do it. I'm preparing for a new job right now lol

**Comment by RetryingOOS** [comment]
Lmao no rush. I just wanna prepare a tool for my group. Do it at your own pace. I would look forward to it. And best of luck to your job! :)

**Comment by RetryingOOS** [comment]
Another issue is that the error message is on an infinite loop. It keeps printing "Error
Please make sure you include an image or video in your post." 

One suggestion could be a leaderboard.

**Comment by JustinELRoberts** [comment]
I'll look into the errors. I didn't really get around to unit testing heavily before kind of putting this on pause which is why I ended up just posting here to open source it :P. I'll def check them out soon tho

**Comment by JustinELRoberts** [comment]
For subsequent errors try to open a new thread for each please :)

**Comment by JustinELRoberts** [comment]
I believe I fixed the original issue this thread was created for. If you don't respond within 24h, I will close the thread and assume all is well.

Additionally, I was unable to reproduce your other issue with infinitely looping error messages in the success channel. My best guess is you might have improperly input the bot's ID, meaning it cant distinguish the bot's own messages from a user's. Below is a screenshot of what I mean when I ask for the bot's "user ID"; it is obtained by right clicking on a user while having the setting for "Developer Mode" enabled under "Appearance" on Discord. I hope this helps!

<img width="178" alt="Screen Shot 2020-07-07 at 15 25 18" src="https://user-images.githubusercontent.com/35182347/86832352-12a19d00-c066-11ea-9252-f416cc42fb5e.png">

**Comment by RetryingOOS** [comment]
Thanks for the help and fix. I think that the issue has been resolved! Thanks a lot. Means a lot to make this open source! Best of luck to your future endeavors!
